"""Certifications list window with add / edit / delete / print actions.

Layout:
    QMainWindow
    ├── toolbar:    Add / Edit / Delete / ─── / Print Selected / Print All
    ├── central:    QTableView bound to CertificationTableModel
    └── status bar

Print pipeline uses Qt's QTextDocument + QPrinter with QPrintDialog, so
the standard macOS print sheet appears (printer selection, paper size,
PDF export). The HTML for each cert is generated by `_render_html()`;
multiple certs are concatenated with a page break between them.

This module is intentionally printer-side-effect free — the rendering
function returns a string, the window is responsible for piping it to
the printer. That keeps it testable.
"""

from __future__ import annotations

import html
import sqlite3
from collections.abc import Iterable
from datetime import date

from PySide6.QtCore import QAbstractTableModel, QModelIndex, Qt
from PySide6.QtGui import QAction, QKeySequence, QTextDocument
from PySide6.QtPrintSupport import QPrinter, QPrintDialog
from PySide6.QtWidgets import (
    QHeaderView,
    QMainWindow,
    QMessageBox,
    QStatusBar,
    QTableView,
    QToolBar,
)

from open_dive_log.repositories import certifications
from open_dive_log.ui.cert_add_edit_dialog import CertAddEditDialog


# (header text, tooltip, list-of-column-getters-on-Certification)
HEADERS: tuple[tuple[str, str], ...] = (
    ("Date",          "Certification date (YYYY-MM-DD)."),
    ("Cert",          "Certification name."),
    ("Number",        "Agency-issued certification number."),
    ("Agency",        "Certifying agency."),
    ("Facility",      "Dive shop / training center (free text)."),
    ("Instructor",    "Instructor's name (free text)."),
)


class CertificationTableModel(QAbstractTableModel):
    """Read-only model over `certifications.list_all`."""

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._rows: list[certifications.Certification] = []

    def set_rows(self, rows: Iterable[certifications.Certification]) -> None:
        self.beginResetModel()
        self._rows = list(rows)
        self.endResetModel()

    def row_at(self, index: int) -> certifications.Certification | None:
        if 0 <= index < len(self._rows):
            return self._rows[index]
        return None

    def rowCount(self, parent: QModelIndex = QModelIndex()) -> int:  # noqa: B008
        if parent.isValid():
            return 0
        return len(self._rows)

    def columnCount(self, parent: QModelIndex = QModelIndex()) -> int:  # noqa: B008
        if parent.isValid():
            return 0
        return len(HEADERS)

    def headerData(self, section: int, orientation: Qt.Orientation, role: int = Qt.ItemDataRole.DisplayRole):
        if role != Qt.ItemDataRole.DisplayRole:
            return None
        if orientation == Qt.Orientation.Horizontal:
            if 0 <= section < len(HEADERS):
                return HEADERS[section][0]
        elif orientation == Qt.Orientation.Vertical:
            return section + 1
        return None

    def data(self, index: QModelIndex, role: int = Qt.ItemDataRole.DisplayRole):
        if not index.isValid() or not (0 <= index.row() < len(self._rows)):
            return None
        cert = self._rows[index.row()]
        col = index.column()

        if role == Qt.ItemDataRole.DisplayRole:
            if col == 0:
                return cert.cert_date
            if col == 1:
                return cert.cert_name
            if col == 2:
                return cert.cert_number
            if col == 3:
                return cert.certifying_agency_name
            if col == 4:
                return cert.certifying_facility or ""
            if col == 5:
                return cert.instructor or ""

        if role == Qt.ItemDataRole.ToolTipRole:
            if 0 <= col < len(HEADERS):
                return HEADERS[col][1]

        if role == Qt.ItemDataRole.UserRole:
            return cert.id

        return None


# ---------------------------------------------------------------------------
# Print rendering — pure HTML, testable without Qt
# ---------------------------------------------------------------------------
def _esc(s: str | None) -> str:
    return html.escape(s) if s else ""


def render_cert_html(cert: certifications.Certification) -> str:
    """Return an HTML string suitable for QTextDocument.setHtml()."""
    rows = [
        ("Date",        cert.cert_date),
        ("Number",      cert.cert_number),
        ("Agency",      cert.certifying_agency_name),
        ("Facility",    cert.certifying_facility),
        ("Instructor",  cert.instructor),
    ]
    row_html = "\n".join(
        f"<tr><th align='right'>{_esc(k)}:</th><td>{_esc(v) if v else '<i>(not recorded)</i>'}</td></tr>"
        for k, v in rows
    )
    notes_block = (
        f"<h3>Notes</h3><p>{_esc(cert.notes)}</p>"
        if cert.notes else ""
    )
    return f"""
        <html><body>
            <h1 style='text-align: center;'>{_esc(cert.cert_name)}</h1>
            <p style='text-align: center; color: #555;'>
                {_esc(cert.certifying_agency_name)} · {_esc(cert.cert_date)}
            </p>
            <hr>
            <table cellspacing='4' cellpadding='4' width='100%'>{row_html}</table>
            {notes_block}
            <hr>
            <p style='font-size: 9pt; color: #888; text-align: center;'>
                Generated from Open Dive Log on {date.today().isoformat()}
            </p>
        </body></html>
    """


def render_certs_html(certs: list[certifications.Certification]) -> str:
    """Concatenate multiple certs with a page break between them."""
    if not certs:
        return "<html><body><p>No certifications to print.</p></body></html>"
    parts = [render_cert_html(c) for c in certs]
    if len(parts) == 1:
        return parts[0]
    # QTextDocument honors the page-break-before CSS property.
    return parts[0] + "\n".join(
        # page break + drop the redundant <html><body> tags for inline concatenations
        p.replace("<html><body>", "<div style='page-break-before: always;'>")
         .replace("</body></html>", "</div>")
        for p in parts[1:]
    )


# ---------------------------------------------------------------------------
# Window
# ---------------------------------------------------------------------------
class CertListWindow(QMainWindow):
    def __init__(self, conn: sqlite3.Connection, parent=None) -> None:
        super().__init__(parent)
        self._conn = conn
        self.setWindowTitle("Certifications")
        self.resize(960, 540)

        # --- Model + table ---
        self._model = CertificationTableModel(self)
        self._table = QTableView(self)
        self._table.setModel(self._model)
        self._table.setSelectionBehavior(QTableView.SelectionBehavior.SelectRows)
        self._table.setSelectionMode(QTableView.SelectionMode.SingleSelection)
        self._table.setEditTriggers(QTableView.EditTrigger.NoEditTriggers)
        self._table.setAlternatingRowColors(True)
        self._table.verticalHeader().setVisible(False)
        header = self._table.horizontalHeader()
        header.setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        header.setStretchLastSection(True)
        self._table.doubleClicked.connect(self._on_row_double_clicked)
        self.setCentralWidget(self._table)

        # --- Toolbar ---
        toolbar = QToolBar("Certifications toolbar", self)
        toolbar.setObjectName("CertificationsToolbar")
        self.addToolBar(toolbar)

        self._action_add = QAction("&Add", self)
        self._action_add.setShortcut(QKeySequence.StandardKey.New)
        self._action_add.triggered.connect(self._on_add)
        toolbar.addAction(self._action_add)

        self._action_edit = QAction("&Edit", self)
        self._action_edit.setShortcut(QKeySequence("Ctrl+E"))
        self._action_edit.triggered.connect(self._on_edit)
        toolbar.addAction(self._action_edit)

        self._action_delete = QAction("&Delete", self)
        self._action_delete.setShortcut(QKeySequence.StandardKey.Delete)
        self._action_delete.triggered.connect(self._on_delete)
        toolbar.addAction(self._action_delete)

        toolbar.addSeparator()
        self._action_print_selected = QAction("&Print Selected", self)
        self._action_print_selected.setShortcut(QKeySequence.StandardKey.Print)
        self._action_print_selected.triggered.connect(self._on_print_selected)
        toolbar.addAction(self._action_print_selected)

        self._action_print_all = QAction("Print &All", self)
        self._action_print_all.triggered.connect(self._on_print_all)
        toolbar.addAction(self._action_print_all)

        self.setStatusBar(QStatusBar(self))
        self.refresh()

    # ------------------------------------------------------------------
    # Data + actions
    # ------------------------------------------------------------------
    def refresh(self) -> None:
        rows = certifications.list_all(self._conn)
        self._model.set_rows(rows)
        self.statusBar().showMessage(f"{len(rows)} certification(s)")

    def _selected_cert(self) -> certifications.Certification | None:
        idx = self._table.currentIndex()
        if not idx.isValid():
            return None
        return self._model.row_at(idx.row())

    def _on_row_double_clicked(self, index) -> None:
        if index.isValid():
            self._on_edit()

    def _on_add(self) -> None:
        dlg = CertAddEditDialog(self._conn, cert=None, parent=self)
        if dlg.exec() != CertAddEditDialog.DialogCode.Accepted:
            return
        submitted = dlg.result_cert()
        if submitted is None:
            return
        new_id = certifications.create(self._conn, **submitted.__dict__)
        self.refresh()
        # Highlight the new row for visual feedback.
        for r in range(self._model.rowCount()):
            if self._model.row_at(r) and self._model.row_at(r).id == new_id:
                self._table.selectRow(r)
                break
        self.statusBar().showMessage(f"Added certification #{new_id}", 5000)

    def _on_edit(self) -> None:
        cert = self._selected_cert()
        if cert is None:
            QMessageBox.information(self, "Edit", "Select a certification first.")
            return
        dlg = CertAddEditDialog(self._conn, cert=cert, parent=self)
        if dlg.exec() != CertAddEditDialog.DialogCode.Accepted:
            return
        submitted = dlg.result_cert()
        if submitted is None:
            return
        certifications.update(self._conn, cert.id, **submitted.__dict__)
        self.refresh()
        self.statusBar().showMessage(f"Updated certification #{cert.id}", 5000)

    def _on_delete(self) -> None:
        cert = self._selected_cert()
        if cert is None:
            QMessageBox.information(self, "Delete", "Select a certification first.")
            return
        answer = QMessageBox.question(
            self,
            "Delete certification",
            f"Delete '{cert.cert_name}' ({cert.certifying_agency_name}, "
            f"{cert.cert_date})? This cannot be undone.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.Cancel,
        )
        if answer != QMessageBox.StandardButton.Yes:
            return
        certifications.delete(self._conn, cert.id)
        self.refresh()
        self.statusBar().showMessage(f"Deleted certification #{cert.id}", 5000)

    def _on_print_selected(self) -> None:
        cert = self._selected_cert()
        if cert is None:
            QMessageBox.information(
                self, "Print", "Select a certification first, or use 'Print All'."
            )
            return
        self._print_html(render_cert_html(cert), job_title=f"Print: {cert.cert_name}")

    def _on_print_all(self) -> None:
        rows = certifications.list_all(self._conn)
        if not rows:
            QMessageBox.information(self, "Print All", "No certifications to print.")
            return
        self._print_html(render_certs_html(rows), job_title="Print: All Certifications")

    def _print_html(self, html_doc: str, *, job_title: str) -> None:
        """Common print pipeline: show QPrintDialog, render the HTML, send to printer."""
        printer = QPrinter(QPrinter.PrinterMode.HighResolution)
        printer.setDocName(job_title)
        dialog = QPrintDialog(printer, self)
        dialog.setWindowTitle(job_title)
        if dialog.exec() != QPrintDialog.DialogCode.Accepted:
            return
        doc = QTextDocument(self)
        doc.setHtml(html_doc)
        doc.print_(printer)
        self.statusBar().showMessage(f"Sent to printer: {job_title}", 5000)
